---
elasticsearch: 
    feeder: 
        srcdir: C:/Users/danu/Documents/2014_EUMETSAT/metadata
        tempdirnameprefix: eumetsat-pn-json-results_
        endpoint:
            cluster.name: eumetsat-cluster
            host: localhost
            port: 9300
            index: eumetsat-catalogue
            type: product
        

...