---
solr:
    app:
        port: 5678
        searchendpoint:
            url: http://localhost:8983/solr/
            collection: eumetsat
            paths:
                search: /query
                productinfo: /get
        name: Solr
        # must match webapp name in servlet container:
        path: solr
    feedOnStart: false
    feedIfEmpty: true
    #embedded:
    #    xml: solr.xml
    #    home: /
