---
solr: 
    feeder: 
        srcdir: C:/Users/danu/Documents/2014_EUMETSAT/metadata
        tempdirnameprefix: eumetsat-pn-json-results_
        endpoint:
            cluster.name: eumetsat-cluster
            url: http://localhost:8983/solr/
            index: eumetsat-catalogue
            type: product
        # set this to false to not send documents to index
        index: false
        

...